apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      volumes:
        - name: reports-storage
          persistentVolumeClaim:
            claimName: reports-nfs-pvc
      containers:
        - name: celery-worker
          image: andrei8080/webserver:latest
          command: ["poetry", "run", "celery", "-A", "app.tasks", "worker", "--loglevel=info"]
          envFrom:
            - secretRef:
                name: smtp-secret
            - configMapRef:
                name: webserver-config
          volumeMounts:
            - name: reports-storage
              mountPath: /app/reports