apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: andrei8080/webserver:latest
          command: ["poetry", "run", "celery", "-A", "app.tasks.celery_app", "worker", "--loglevel=info"]
          envFrom:
            - configMapRef:
                name: webserver-config