apiVersion: v1
kind: PersistentVolume
metadata:
  name: reports-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.255.100
    path: /srv/nfs/reports
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reports-nfs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
