apiVersion: v1
kind: ConfigMap
metadata:
  name: webserver-config
data:
  API_VERSION: "1.0.0"
  PROJECT_NAME: "webserver"
  ENV: "prod"
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8000"
  REDIS_HOST: redis-nfs.default.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
