apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      volumes:
        - name: frontend-volume
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config
      initContainers:
        - name: frontend-build
          image: andrei8080/frontend:latest
          command: ["/bin/sh", "-c"]
          args:
            - cp -r /app/build/* /usr/share/nginx/html/
          volumeMounts:
            - name: frontend-volume
              mountPath: /usr/share/nginx/html
      containers:
        - name: webserver
          image: andrei8080/webserver:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: webserver-config

        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: frontend-volume
              mountPath: /usr/share/nginx/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  selector:
    app: webserver
  clusterIP: 10.105.206.131
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-service-external
spec:
  type: NodePort
  selector:
    app: webserver
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
