apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          image: 192.168.255.200:5000/webserver
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: webserver-config
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: webserver
  type: ClusterIP

