apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: app-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 999
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: keycloak-tls
      hosts:
        # - "keycloak.192.168.255.48.nip.io"
        # - "webserver.192.168.255.48.nip.io"
        - "kc.linuxtecha.xyz"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak-vs
spec:
  hosts:
    # - "keycloak.192.168.255.48.nip.io"
    - "kc.linuxtecha.xyz"
  gateways:
    - app-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: keycloak-service
            port:
              number: 88
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: webserver-vs
spec:
  hosts:
    - "webserver.192.168.255.48.nip.io"
  gateways:
    - app-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: webserver-service
            port:
              number: 80
